version: '3'
services:

  nginx-proxy:
    build: 
      context: ./nginx-proxy
      dockerfile: ./dockerfile
    image: nginx-proxy
    container_name: nginx-proxy-container
    ports:
      - "8080:8080" # bin-app
      - "4000:4000" # welcome-api
      - "4001:4001" # bof1-api
      - "4002:4002" # bof2-api
      - "5000:5000" # rop1-api
      - "5001:5001" # rop2-api
    restart: always
    depends_on:
      - bin-upload
      - welcome-api
      - bof1-api
      - bof2-api
      - rop1-api
      - rop2-api

  welcome-api:
    build: 
      context: ./welcome-api
      dockerfile: ./dockerfile
    container_name: welcome-api-container
    restart: always

  bof1-api:
    build: 
      context: ./bof1-api
      dockerfile: ./dockerfile
    container_name: bof1-api
    depends_on:
      - bin-upload
    restart: always

  bof2-api:
    build: 
      context: ./bof2-api
      dockerfile: ./dockerfile
    container_name: bof2-api
    depends_on:
      - bin-upload
    restart: always

  bin-upload:
    build:
      context: ./bin-upload
      dockerfile: ./dockerfile
    container_name: bin-upload-container
    restart: always

  rop1-api:
    build: 
      context: ./rop1-api
      dockerfile: ./dockerfile
    container_name: rop1-api-container
    depends_on:
      - bin-upload
    restart: always

  rop2-api:
    build: 
      context: ./rop2-api
      dockerfile: ./dockerfile
    container_name: rop2-api-container
    depends_on:
      - bin-upload
    restart: always


  # bottle-app:
  #   build: 
  #     context: ./bottle-app
  #     dockerfile: ./dockerfile
  #   image: bottle-app
  #   container_name: bottle-app-container
  # mysql-db:
  #   build: ./mysql-db
  #   image: mysql
  #   container_name: mysql-db-container
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mysql
  # c-api:
  #   build: 
  #     context: ./c-api
  #     dockerfile: ./dockerfile
  #   image: c-api
  #   container_name: c-api-container