FROM common-capi
COPY ./files/ /opt/app/
WORKDIR /opt/app/
ENV src=rop1.c
ENV out=chall.elf
ENV hidden_src=hidden_rop1.c
ENV hidden_out=rop1.elf
ENV linked="/lib64/ld-linux-x86-64.so.2"
USER bob
CMD     gcc ${src} -fno-stack-protector -no-pie -o ${out} 2>/dev/null && \
        gcc ${hidden_src} -fno-stack-protector -no-pie -o ${hidden_out} 2>/dev/null && \
        curl -X POST -F upload=@./${hidden_out} http://bin-upload:8080/upload && \
        curl -X POST -F upload=@./${hidden_src} http://bin-upload:8080/upload && \
        curl -X POST -F upload=@${linked} http://bin-upload:8080/upload && \
        socat TCP-L:4000,reuseaddr,fork EXEC:./${out}