FROM common-capi
COPY ./files/ /opt/app/
WORKDIR /opt/app/
ENV src=bof.c
ENV out=chall.elf
ENV hidden_src=hidden_bof.c
ENV hidden_out=bof.elf
USER bob
CMD     gcc ${src} -fno-stack-protector -no-pie -o ${out} 2>/dev/null && \
        gcc ${hidden_src} -fno-stack-protector -no-pie -o ${hidden_out} 2>/dev/null && \
        curl -X POST -F upload=@./${hidden_out} http://bin-upload:8080/upload && \
        socat TCP-L:4000,reuseaddr,fork EXEC:./${out}