FROM ubuntu:22.04
RUN apt update && \
    apt-get install build-essential -y && \ 
    apt-get install socat -y && \
    apt-get install curl -y && \
    mkdir /opt/app && \
    chmod 777 /opt/app && \
    adduser bob